services:
  app:
    image: "sjc.vultrcr.com/dongregistry/blog_back:latest"
    # build:
      # context: .
      # dockerfile: Dockerfile
    container_name: blog_back
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 9473
    # ports:
    #   - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./.env:/home/node/.env
      - ./log:/home/node/log
    networks:
      - proxy

networks:
  proxy:
    external: true
